src/pages/amritseries/index.js, src/styles/CaseStudy.scss
converted mail text of amrit series page to anchor tag
Fixes #3
=> converted mail text of amrit series page of anchor tag

package.json, src/styles/BlogDetails.scss, src/styles/JoinUsBannerImage.scss, src/styles/index.scss
removed extra space from the blog page 
Fixes #12
=> removed extra space from the blog page

package.json, src/components/CareerPageComponents/PaginationSlider/PaginationSlider.js
have added autoslide carousal feature in careers page 
Fixes #13
=> autoslide carousal feature 

src/pages/amritseries/go-sugam.md, src/pages/amritseries/hkrn.md, src/templates/case-study.js, static/admin/config.yml
Added optional testimonial and side navbar feature in new case study
Fixes #16
=> Testimonial and side navbar

static/admin/config.yml
Have changed Display on Home field to optional in media page
Fixes #18
=> Display on Home field

src/cms/cms.js, src/cms/preview-templates/OldCaseStudyPreview.js, src/components/ProductPageComponents/OurPublicationsSection/OurPublicationsSection.js, src/templates/old-case-study.js, static/admin/config.yml
added case study preview for case studies
Fixes #16
=> added case study preview for case studies

src/components/CaseStudyComponents/SuccessStoriesSection.js, src/pages/amritseries/antyodaya-saral.md, src/pages/amritseries/go-sugam.md, src/pages/amritseries/hkrn.md, src/pages/amritseries/ksk.md, src/pages/amritseries/test2.md, src/templates/case-study.js, src/templates/old-case-study.js, static/admin/config.yml
added customised success stories feature for case-studies
fixes #16
=> added customised success stories feature for case-studies

static/admin/config.yml
=> edited default list limit

src/templates/case-study.js, src/templates/old-case-study.js
added image condition for case study rhs preview
=> added image condition for case study rhs preview

src/pages/amritseries/antyodaya-saral.md, src/templates/old-case-study.js
ui changes done in old-case template
=> ui changes done in old-case template

src/pages/amritseries/antyodaya-saral.md
background image changed to null in place of empty string
=> background image changed to null in place of empty string

src/components/Navbar.js
=> added c4gt page in the navbar

src/cms/cms.js, src/cms/preview-templates/AssetPagePreview.js, src/templates/our-assets-page.js
added preview page for asset page
=> added preview page for asset page

src/pages/amritseries/antyodaya-saral.md, src/pages/amritseries/test2.md, src/templates/case-study.js, src/templates/old-case-study.js, static/admin/config.yml
changes done in infographic images
=> changes done in infographic images

src/components/Footer.js, src/components/HeaderSmall.js, src/components/Navbar.js
Added asset and decluttered page in website's footer and navbar
=> Asset and Decluttered Page

src/pages/amritseries/cmgga-amrit-series.md, src/pages/amritseries/saksham-phase-1.md, static/admin/config.yml
some fields were not added in the cmgga.md
=> bugfix case-study

src/components/Footer.js, src/components/HeaderSmall.js, src/components/Navbar.js
=> tgc redirection url changed

src/cms/cms.js, src/components/ProductPageComponents/OurPublicationsSection/OurPublicationsSection.js, src/pages/our-team/index.md, src/styles/OurTeam.scss, src/templates/our-team.js, src/templates/project-post.js, static/admin/config.yml
=> fix/ rollback fix

src/styles/OurTeam.scss
=> Fix/ margin fixed for the team list container

src/components/JoinUsPageComponents/JoinUsFormSection/JoinUsFormSection.js
=> last info line removed from the join us page

src/cms/preview-templates/BlogPostPreview.js
=> blog-post bugFix

src/components/Footer.js, src/components/HeaderSmall.js
=> team page redirection issue fixed

src/templates/our-team.js
=> card overflow issue solved

src/cms/cms.js, src/cms/preview-templates/Careers2PagePreview.js, src/components/HeaderSmall.js, src/components/Navbar.js, src/components/appList.jsx, src/components/journeySofar.jsx, src/components/solutionsBuilt.jsx, src/pages/samagrax/index.md, src/templates/careers2-page.js, static/admin/config.yml
=> Samagra X page was made
